-- MySQL Script generated by MySQL Workbench
-- Fri Apr 19 18:42:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Brand_Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand_Group` (
  `idBrand_Group` INT NOT NULL,
  `BrGrName` VARCHAR(45) NULL,
  PRIMARY KEY (`idBrand_Group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `num` INT NOT NULL,
  `floor` VARCHAR(10) NULL,
  `door` VARCHAR(10) NULL,
  `city` VARCHAR(45) NOT NULL,
  `postcode` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `supName` VARCHAR(45) NULL,
  `supTel` INT NULL,
  `supFax` INT NULL,
  `supNif` VARCHAR(9) NOT NULL,
  `Brand_Group_idBrand_Group` INT NOT NULL,
  `Address_idAddress` INT NOT NULL,
  PRIMARY KEY (`idSupplier`),
  INDEX `fk_Supplier_Brand_Group1_idx` (`Brand_Group_idBrand_Group` ASC) VISIBLE,
  INDEX `fk_Supplier_Address1_idx` (`Address_idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_Brand_Group1`
    FOREIGN KEY (`Brand_Group_idBrand_Group`)
    REFERENCES `mydb`.`Brand_Group` (`idBrand_Group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supplier_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `mydb`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mount` (
  `idMount` INT NOT NULL,
  `mount_type` VARCHAR(45) NULL,
  PRIMARY KEY (`idMount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `idBrand` INT NOT NULL,
  `brandName` VARCHAR(45) NULL,
  `Brand_Group_idBrand_Group` INT NOT NULL,
  PRIMARY KEY (`idBrand`),
  INDEX `fk_Brand_Brand_Group1_idx` (`Brand_Group_idBrand_Group` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_Brand_Group1`
    FOREIGN KEY (`Brand_Group_idBrand_Group`)
    REFERENCES `mydb`.`Brand_Group` (`idBrand_Group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Glasses` (
  `idGlasses` INT NOT NULL AUTO_INCREMENT,
  `gradL` VARCHAR(10) NULL,
  `gradR` VARCHAR(10) NULL,
  `mountColor1` VARCHAR(10) NULL,
  `mountColor2` VARCHAR(10) NULL,
  `price` VARCHAR(45) NULL,
  `Mount_idMount` INT NOT NULL,
  `Brand_idBrand` INT NOT NULL,
  PRIMARY KEY (`idGlasses`),
  INDEX `fk_Glasses_Mount1_idx` (`Mount_idMount` ASC) VISIBLE,
  INDEX `fk_Glasses_Brand1_idx` (`Brand_idBrand` ASC) VISIBLE,
  CONSTRAINT `fk_Glasses_Mount1`
    FOREIGN KEY (`Mount_idMount`)
    REFERENCES `mydb`.`Mount` (`idMount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Brand1`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `mydb`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL,
  `clName` VARCHAR(45) NULL,
  `clTel` INT NOT NULL,
  `clEmail` VARCHAR(45) NULL,
  `recom` VARCHAR(45) NULL,
  `Address_idAddress` INT NOT NULL,
  `regDate` DATE NOT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `fk_Client_Address1_idx` (`Address_idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `mydb`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `idEmployee` INT NOT NULL,
  `empName` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_header`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_header` (
  `idOrder` INT NOT NULL,
  `orderDate` DATETIME NULL,
  `Employee_idEmployee` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `Supplier_idSupplier` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_Order_header_Employee1_idx` (`Employee_idEmployee` ASC) VISIBLE,
  INDEX `fk_Order_header_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  INDEX `fk_Order_header_Supplier1_idx` (`Supplier_idSupplier` ASC) VISIBLE,
  CONSTRAINT `fk_Order_header_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `mydb`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_header_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_header_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `mydb`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_item` (
  `Order_header_idOrder` INT NOT NULL,
  `itemNum` INT NOT NULL,
  `Glasses_idGlasses` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`Order_header_idOrder`, `itemNum`),
  INDEX `fk_Order_item_Order_header_idx` (`Order_header_idOrder` ASC) VISIBLE,
  INDEX `fk_Order_item_Glasses1_idx` (`Glasses_idGlasses` ASC) VISIBLE,
  CONSTRAINT `fk_Order_item_Order_header`
    FOREIGN KEY (`Order_header_idOrder`)
    REFERENCES `mydb`.`Order_header` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_item_Glasses1`
    FOREIGN KEY (`Glasses_idGlasses`)
    REFERENCES `mydb`.`Glasses` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
